In [1]:
!pip install numpy



Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python3 -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
np.__version__


'1.25.1'

In [4]:
arr=np.zeros(10)

In [5]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
arr1=np.arange(10)

arr1.itemsize*arr1.size

80

In [7]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [8]:
arr1[4]=1
arr1

array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

In [9]:
arr2=np.arange(10,49)
arr2


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [10]:
np.flip(arr1)

array([9, 8, 7, 6, 5, 1, 3, 2, 1, 0])

In [11]:
arr3=np.arange(0,9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr4=np.array([1,2,0,0,4,0])
arr4[arr4!=0]
np.where(arr4!=0)[0] #for firt index only [0][0] and for all only one[0]

array([0, 1, 4])

In [13]:
arr5=np.identity(3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr5=np.random.uniform(0,27,27).reshape(3,3,3)
arr5.astype(int) # by defalt float
arr5

array([[[ 5.22160769,  6.00894698, 11.26982641],
        [ 7.67885587,  6.2753997 ,  5.41113661],
        [19.03149631,  3.94883399, 17.16899657]],

       [[15.7628633 , 17.13217422,  4.03663919],
        [ 0.87439765, 15.97619682, 25.15262933],
        [23.19470386, 13.99611247, 15.56882148]],

       [[20.53073112, 18.78183923, 26.96271294],
        [26.73441429,  1.04435145, 20.85979869],
        [ 2.12586808, 21.34042296,  7.58628634]]])

In [15]:
arr6=np.random.randint(0,100,27).reshape(3,3,3)
#arr6.shape
#arr6.ndim
#arr6.reshape(3,3,3)
arr6

array([[[ 4, 98, 92],
        [32, 68, 97],
        [30, 94, 46]],

       [[95, 26, 74],
        [67,  8, 90],
        [12, 95, 93]],

       [[62, 35, 45],
        [81, 68,  7],
        [78, 75, 72]]])

In [16]:
arr7=np.random.randint(0,200,100).reshape(10,10)
print(arr7)
print(np.max(arr7))
print(np.min(arr7))




[[  4 122 188 114 168  56   8 165   5  94]
 [ 73  29 104 181 130  10  15  99 116 181]
 [ 37  48 197  65  54  96 181  79 149 162]
 [  2 147 196  39 123  43  34 106 152  27]
 [ 94  30 124   2  19  99  52 140  83 181]
 [ 51 166 169 157 136 157 188 164  96 154]
 [ 85 149  54  13  30 107  81  76 197 108]
 [151 135 120 190  31 157  87 121 103  24]
 [199  36 179   3 151 130 184  10  77  70]
 [135 117  39 197  89  27 133 150 108 160]]
199
2


In [17]:
arr8=np.random.randint(1,60,30)
print(arr8)
np.mean(arr8)


[57 19 37 47 51 27 54 15  7 18  7 10 56 52 19 15 50 32 27 35 12 53 34  7
 31 24 30 38 15 31]


30.333333333333332

In [18]:
arr9=np.zeros(16).reshape(4,4).astype(int)

arr9[:1]=1#row
arr9[3:]=1#row
arr9[:,:1]=1#column
arr9[:,3:]=1#column
arr9

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [19]:
arr9[1:3,1:3]# row column
# slicing  [1:3->1,2] 3 is not included

array([[0, 0],
       [0, 0]])

In [20]:
arr6

array([[[ 4, 98, 92],
        [32, 68, 97],
        [30, 94, 46]],

       [[95, 26, 74],
        [67,  8, 90],
        [12, 95, 93]],

       [[62, 35, 45],
        [81, 68,  7],
        [78, 75, 72]]])

In [21]:
print(arr6[:1:2,1])
print(arr6[2:3,:,1]) # in 3d array[matri,row,column]->[m:m,r:r,c:c]

[[32 68 97]]
[[35 68 75]]


In [22]:
arr3



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr3[:1]=0
arr3[2:]=0
arr3[:,:1]=0
arr3[:,2:]=0
arr3

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 0]])

In [24]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)

print(np.nan-np.nan)
print(np.nan in  set([np.nan]))
print(0.3==3*0.1)


nan
False
False
nan
True
False


In [25]:
arr10=np.ones((5,5)).astype(int)
for i in range(5):
  for j in range(5):
    if i>j:
     arr10[i][j]=i
arr10

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [2, 2, 1, 1, 1],
       [3, 3, 3, 1, 1],
       [4, 4, 4, 4, 1]])

In [26]:
arr11=np.ones((4,4)).astype(int)
print(np.tril(arr11,0),"\n") # lower triangular matrix
print(np.triu(arr11,0)) # upper triangular matrix

[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]] 

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


In [27]:
arr12=np.zeros((8,8)).astype(int)

arr12[1::2,::2]=1 
arr12[::2,1::2]=1
arr12


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [28]:
arr7

array([[  4, 122, 188, 114, 168,  56,   8, 165,   5,  94],
       [ 73,  29, 104, 181, 130,  10,  15,  99, 116, 181],
       [ 37,  48, 197,  65,  54,  96, 181,  79, 149, 162],
       [  2, 147, 196,  39, 123,  43,  34, 106, 152,  27],
       [ 94,  30, 124,   2,  19,  99,  52, 140,  83, 181],
       [ 51, 166, 169, 157, 136, 157, 188, 164,  96, 154],
       [ 85, 149,  54,  13,  30, 107,  81,  76, 197, 108],
       [151, 135, 120, 190,  31, 157,  87, 121, 103,  24],
       [199,  36, 179,   3, 151, 130, 184,  10,  77,  70],
       [135, 117,  39, 197,  89,  27, 133, 150, 108, 160]])

In [29]:
print(arr7[1::2]) # leaves one row     [start::num] num-> number of row ? col leave num-1 i.e num=2 ,leave = 1
print(arr7[:,::2]) # leaves one column
print(arr7[1::2,::2])

[[ 73  29 104 181 130  10  15  99 116 181]
 [  2 147 196  39 123  43  34 106 152  27]
 [ 51 166 169 157 136 157 188 164  96 154]
 [151 135 120 190  31 157  87 121 103  24]
 [135 117  39 197  89  27 133 150 108 160]]
[[  4 188 168   8   5]
 [ 73 104 130  15 116]
 [ 37 197  54 181 149]
 [  2 196 123  34 152]
 [ 94 124  19  52  83]
 [ 51 169 136 188  96]
 [ 85  54  30  81 197]
 [151 120  31  87 103]
 [199 179 151 184  77]
 [135  39  89 133 108]]
[[ 73 104 130  15 116]
 [  2 196 123  34 152]
 [ 51 169 136 188  96]
 [151 120  31  87 103]
 [135  39  89 133 108]]


In [30]:
arr13=np.arange(336).astype(int).reshape(6,7,8)
s=np.argwhere(arr13==100) # to find index
s
#arr13[5][6][7]

array([[1, 5, 4]])

In [31]:
arr14=np.random.randint(0,50,25).reshape(5,5)
#np.ravel(arr14)
arr14/np.linalg.norm(arr14)

array([[0.15367408, 0.13172064, 0.32198378, 0.01463563, 0.20489877],
       [0.25612346, 0.00731781, 0.07317813, 0.19026314, 0.34393722],
       [0.30734816, 0.08049595, 0.13172064, 0.31466597, 0.3293016 ],
       [0.13172064, 0.03658907, 0.19026314, 0.02927125, 0.13172064],
       [0.14635627, 0.18294533, 0.35857285, 0.04390688, 0.05854251]])

In [32]:
color=np.dtype([("r",np.ubyte),
               ("g",np.ubyte),
               ("b",np.ubyte),
               ("a",np.ubyte)])
 # def __str__(self):
  #  return f"returns string"
        
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [33]:
ar1=np.arange(15).reshape(5,3)
ar2=np.arange(6).reshape(3,2)
print(np.dot(ar1,ar2)) #multiply
# Alternative
z=ar1@ar2
print(z)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [34]:
arr15=np.arange(10).astype(int)
for i in np.nditer(arr15):
    if i>3 and i<8:
      arr15[i]=np.negative(i)
print(arr15)
# alternative
arr15[(arr15>3) & (arr15<8)] *= -1 #pranthesis is important in indexing method, if more than one condition
arr15
# best method alternative
# * m= (arr15>3) & (arr15<8)
#arr15[m] *= -1
#np.any() or np.all() return bool

[ 0  1  2  3 -4 -5 -6 -7  8  9]


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

In [35]:
print(sum(range(5),-1))
from numpy import * # after this sum function do not go for second argument i.e -1
print(sum(range(5),-1))

9
10


In [36]:
z=np.arange(6)
z**z # valid output 1,1,2**2,3**3,4**4
2<<z>>2 # valid
z<-z# valid
1j*z #valid
z/1/1# valid
#z<z>z # invalid

array([0., 1., 2., 3., 4., 5.])

In [37]:
#np.array(0)/np.array(0)
#np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_58294/3645838774.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [38]:

arr15=np.random.uniform(-10,10,10)
np.copysign(np.ceil(np.abs(arr15)),arr15) #  copysign(x,y) copy's sign from y to x and abs remove - sign

array([-1., -7.,  1.,  5.,  8.,  9., -6.,  5., -9.,  9.])

In [39]:
a1=np.arange(10).reshape(2,5)
a2=np.arange(20).reshape(2,10)
np.intersect1d(a1,a2) # it work with 1d ,2d etc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
dft=np.seterr(all='ignore')
z=np.ones(1)/0
_ = np.seterr(**dft)
with np.errstate(all='ignore'):
  np.arange(3)/0

In [41]:
np.sqrt(-1)==np.emath.sqrt(-1)

/tmp/ipykernel_58294/3898620780.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

In [42]:
y=np.datetime64('today')-np.timedelta64(1)
t=np.datetime64('today')
tu=np.datetime64('today')+np.timedelta64(1)
print(y,t,tu)

2023-07-27 2023-07-28 2023-07-29


In [43]:
xyz=np.arange('2020-01','2020-02',dtype='datetime64[D]') # fetch D,M,Y ,day=01 i.e two digit np.timedelta64()
#return digit/int
xyz

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
       '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
       '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
       '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
       '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
       '2020-01-29', '2020-01-30', '2020-01-31'], dtype='datetime64[D]')

In [44]:
jul=np.arange('2016-07','2016-08',dtype='datetime64[D]') # month should be in two digit
jul

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [45]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=b) # out makes change in original array and copy to b eg :out=b 
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

In [46]:
arr16=np.random.uniform(10,20,10).reshape(2,5)
print(arr16.astype(int),"\n")
print(arr16//1,"\n")
print(arr16-arr16%1,"\n")
print(np.floor(arr16),"\n")
print(np.trunc(arr16))

[[14 13 14 15 10]
 [13 18 16 16 12]] 

[[14. 13. 14. 15. 10.]
 [13. 18. 16. 16. 12.]] 

[[14. 13. 14. 15. 10.]
 [13. 18. 16. 16. 12.]] 

[[14. 13. 14. 15. 10.]
 [13. 18. 16. 16. 12.]] 

[[14. 13. 14. 15. 10.]
 [13. 18. 16. 16. 12.]]


In [47]:
arr17=np.zeros((5,5))
arr17+=np.arange(5) # broadcasting
print(arr17)
 # without broadcasting
arr17=np.tile(np.arange(5),(5,1))
print(arr17)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [48]:
# tile
til=np.tile([1,2,3,4],(5,1)) # arguments (array,(row,col))
til

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [49]:
def generate():
   for x in range(10):
       yield x
    

arr18=np.fromiter(generate(),dtype=int) # first argument iterator 
print(arr18)


[0 1 2 3 4 5 6 7 8 9]


In [50]:
arr19=np.linspace(0,1,10,endpoint=False)[1:]
#alternative
#arr19=np.linspace(0.1,1,10,endpoint=False)
arr19

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [51]:
arr20=np.random.random(10)
arr20.sort()
arr20

array([0.14729935, 0.18909095, 0.23358307, 0.35343477, 0.55731193,
       0.63561738, 0.64680683, 0.70373267, 0.71715988, 0.76894657])

In [52]:
arr21=np.arange(10)
np.add.reduce(arr21)# faster
#np.sum(arr21) slower



45

In [53]:
a1=np.random.randint(0,2,5)
a2=np.random.randint(0,2,5)
eq=np.allclose(a1,a2)  # it checks for shape nan is not ignore returns false has some tolerancea
print(eq)

eq=np.array_equal(a1,a2) # it checks both shape and value(exactly equal)
print(eq)

False
False


In [54]:
arr22=np.zeros(10)
arr22.flags.writeable=False # makes immutable(read only dataqa)
arr22[1]=2

ValueError: assignment destination is read-only

In [ ]:
arr23=np.random.random((10,2)) # produces number between 0-1
x,y=arr23[:,0],arr23[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r,t)

In [ ]:
arr24=np.random.random(10)
print(arr24)
arr24[arr24.argmax()]=0 # argmax also work np.argmax(arr24) or arr24.argmax()
arr24

In [ ]:
arr25=np.zeros((5,5),[('x',float),('y',float)])
arr25['x'],arr25['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
arr25

In [ ]:
arr26=np.arange(8)
y=arr26+0.5
c=1.0/np.subtract.outer(arr26,y)
print(np.linalg.det(c))

In [ ]:
for dtype in [np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
    
print("\n")
for dtype in [np.float32,np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

In [ ]:
np.set_printoptions(threshold=float("inf"))
arr27=np.zeros((40,40))
arr27

In [ ]:
arr28=np.arange(100)
temp=np.random.uniform(0,100)
indx=(np.abs(arr28-temp)).argmin()
print(arr28[indx])


In [ ]:
arr29=np.zeros(10,[("position",[('x',float),
                               ('y',float)]),
                    ('color',[('r',float),
                              ('g',float),
                              ('b',float)
                             ])])
arr29

In [ ]:
!pip install scipy

In [ ]:
arr30=np.random.random((10,2))
x,y=np.atleast_2d(arr30[:,0],arr30[:,1])
d=np.sqrt((x-x.T)**2+(y-y.T)**2)
#print(d)
# much faster with scipy
import scipy
d=scipy.spatial.distance.cdist(arr30,arr30)
print(d)


In [ ]:
arr31=(np.random.rand(10)*100).astype(np.float32)
y=arr31.view(np.int32)
y[:]=arr31
y


In [ ]:
from io import StringIO
st=StringIO('''1, 2, 3, 4, 5
               6,  ,  , 7, 8
                ,  , 9, 10,11
           ''')
arr32=np.genfromtxt(st,delimiter=",",dtype=int)
arr32